---
- name: Update Windows
  hosts: all 
  tasks:
  - name: run WindowsUpdate
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - '*'
      state: installed
      log_path: c:\ansible_wu.log
    register: update_result
  - name: Reboot if required
    win_reboot:
  when: update_result.reboot_required