---
- name: Setup registry
  hosts: all
  gather_facts: no
  tasks:
  - name: Setup App Eventlog MAX size
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\EventLog\Application
      name: MaxSize
      data: 0x1600000
      type: dword